= RelatonEcma

image:https://img.shields.io/gem/v/relaton-ecma.svg["Gem Version", link="https://rubygems.org/gems/relaton-ecma"]
image:https://github.com/relaton/relaton-ecma/workflows/macos/badge.svg["Build Status (macOS)", link="https://github.com/relaton/relaton-ecma/actions?workflow=macos"]
image:https://github.com/relaton/relaton-ecma/workflows/windows/badge.svg["Build Status (Windows)", link="https://github.com/relaton/relaton-ecma/actions?workflow=windows"]
image:https://github.com/relaton/relaton-ecma/workflows/ubuntu/badge.svg["Build Status (Ubuntu)", link="https://github.com/relaton/relaton-ecma/actions?workflow=ubuntu"]
image:https://codeclimate.com/github/relaton/relaton-ecma/badges/gpa.svg["Code Climate", link="https://codeclimate.com/github/relaton/relaton-ecma"]
image:https://img.shields.io/github/issues-pr-raw/relaton/relaton-ecma.svg["Pull Requests", link="https://github.com/relaton/relaton-ecma/pulls"]
image:https://img.shields.io/github/commits-since/relaton/relaton-ecma/latest.svg["Commits since latest",link="https://github.com/relaton/relaton-ecma/releases"]

RelatonEcma is a Ruby gem that search and fetch standards from the https://www.ecma-international.org[European Computer Manufacturers Association].

== Installation

Add this line to your application's Gemfile:

[source,ruby]
----
gem 'relaton-ecma'
----

And then execute:

    $ bundle install

Or install it yourself as:

    $ gem install relaton-ecma

== Usage

=== Search document

[source,ruby]
----
require 'relaton_ecma'

item = RelatonEcma::EcmaBibliography.get 'ECMA-6'
[relaton-ecma] ("ECMA-6") fetching...
[relaton-ecma] ("ECMA-6") found ECMA-6
=> #<RelatonBib::BibliographicItem:0x007fe0c047e340
...

RelatonEcma::EcmaBibliography.get 'ECMA TR/18'
[relaton-ecma] ("ECMA TR/18") fetching...
[relaton-ecma] ("ECMA TR/18") found ECMA TR/18
=> #<RelatonBib::BibliographicItem:0x007ff53d2011a8
...

RelatonEcma::EcmaBibliography.get "ECMA MEM/2021"
[relaton-ecma] ("ECMA MEM/2021") fetching...
[relaton-ecma] ("ECMA MEM/2021") found ECMA MEM/2021
=> #<RelatonBib::BibliographicItem:0x007ff53d240150
...

# Return nil if document doesn't exist.
RelatonEcma::EcmaBibliography.get '1111'
[relaton-ecma] ("1111") fetching...
[relaton-ecma] WARNING no match found online for 1111. The code must be exactly like it is on the standards website.
=> nil
----

=== Serialization

[source,ruby]
----
item.to_xml
"<bibitem id="ECMA-6" type="standard">
  <title format="text/plain" language="en" script="Latn">7-bit Coded Character Set</title>
  <uri type="src">https://www.ecma-international.org/publications/standards/Ecma-006.htm</uri>
  <uri type="doi">http://www.ecma-international.org/publications/files/ECMA-ST/Ecma-006.pdf</uri>
  <docidentifier type="ECMA">ECMA-6</docidentifier>
  <date type="published">
    <on>1991-12</on>
  </date>
  <edition>6</edition>
  ...
</bibitem>"
----

With `bibdata: true` option XML output wrapped with `bibdata` element and `ext` element added.
[source,ruby]
----
item.to_xml bibdata: true
"<bibdata type="standard">
  <title format="text/plain" language="en" script="Latn">7-bit Coded Character Set</title>
  <uri type="src">https://www.ecma-international.org/publications/standards/Ecma-006.htm</uri>
  <uri type="doi">http://www.ecma-international.org/publications/files/ECMA-ST/Ecma-006.pdf</uri>
  <docidentifier type="ECMA">ECMA-6</docidentifier>
  <date type="published">
    <on>1991-12</on>
  </date>
  <edition>6</edition>
  ...
  <ext>
    <doctype>document</doctype>
  </ext>
</bibdata>"
----

=== Parse a file locally

[source,ruby]
----
item = RelatonBib::XMLParser.from_xml File.read("spec/fixtures/bibdata.xml")
=> #<RelatonBib::BibliographicItem:0x007f847dbe2f18
...

item.to_xml bibdata: true
"<bibdata type="standard">
  <title format="text/plain" language="en" script="Latn">7-bit Coded Character Set</title>
  <uri type="src">https://www.ecma-international.org/publications/standards/Ecma-006.htm</uri>
  <uri type="doi">http://www.ecma-international.org/publications/files/ECMA-ST/Ecma-006.pdf</uri>
  <docidentifier type="ECMA">ECMA-6</docidentifier>
  ...
</bibdata>"
----

== Development

After checking out the repo, run `bin/setup` to install dependencies. Then, run `rake spec` to run the tests. You can also run `bin/console` for an interactive prompt that will allow you to experiment.

To install this gem onto your local machine, run `bundle exec rake install`. To release a new version, update the version number in `version.rb`, and then run `bundle exec rake release`, which will create a git tag for the version, push git commits and tags, and push the `.gem` file to [rubygems.org](https://rubygems.org).

== Contributing

Bug reports and pull requests are welcome on GitHub at https://github.com/relaton/relaton-ecma.


== License

The gem is available as open source under the terms of the [MIT License](https://opensource.org/licenses/MIT).
